# Generated by Django 4.2 on 2023-04-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_is_approved_by_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rent_duration',
        ),
    ]
