version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
          path: code

      # Set up a Python virtual environment
      - run:
          name: Set up Python environment
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip3 install --upgrade pip

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            pip3 install -r requirements.txt
            pip3 install pytest pytest-django
            
      # Set the DJANGO_SETTINGS_MODULE environment variable
      - run:
          name: Set DJANGO_SETTINGS_MODULE
          command: |
            export DJANGO_SETTINGS_MODULE=ksgstore.settings
      
      # Run server
      - run:
          name: Run server
          command: |
            python3 manage.py runserver            

      # Run pytest
      - run:
          name: Run pytest
          command: |
            pytest

      # Save test results
      - store_test_results:
          path: test-results.xml

      # Upload artifacts
      - store_artifacts:
          path: test-results.xml
          
workflows:
  version: 2
  build:
    jobs:
      - test
