version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install pytest pytest-django

      - run:
          name: Run tests
          command: |
            pytest

workflows:
  version: 2
  build:
    jobs:
      - test
