version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      # Set up a Python virtual environment
      - run:
          name: Set up Python environment
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install pytest pytest-django

      # Run pytest
      - run:
          name: Run pytest
          command: |
            pytest

      # Save test results
      - store_test_results:
          path: test-results.xml

      # Upload artifacts
      - store_artifacts:
          path: test-results.xml
          
workflows:
  version: 2
  build:
    jobs:
      - test
