# Generated by Django 4.2 on 2023-04-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_approved_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
